- name: print condition
  hosts: local
  vars:
    number: 15
  connection: local
    
  tasks:
    - name: print if number is greater than 10
      ansible.builtin.debug:
        msg: "The number is greater than 10"
      when: number > 10

    - name: print if number is less than 10
      ansible.builtin.debug:
        msg: "The number is less than 10"
      when: number < 10
