- name: create three ec2 instances and r53 records for frontend, backend and mysql
  hosts: local
  connection: local 
  vars:
    subnet_id: subnet-03f5d20441ab8be68
    sg_id: "sg-074acfbaac90a04bc"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
      - mysql
      - backend
      - frontend
    zone: buddymarket.shop
  tasks:
    - name: ansible to install boto3 and botocore
      ansible.builtin.pip:
        name:
        - boto3
        - botocore
        executable: pip3.9
    - name: Launch EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: "t3.micro"
        image_id: "{{ ami_id }}"
        vpc_subnet_id: "{{ subnet_id }}"
        security_group: "{{ sg_id }}"
      loop: "{{ instances }}"
      register: ec2_instances

    - name: Print the output of launched instances
      ansible.builtin.debug:
        msg: "{{ ec2_instances }}"

    - name: Create Route 53 records for backend with private ip and mysql with private ip
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ item.item }}.{{ zone }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        overwrite: yes
        wait: true
      loop: "{{ ec2_instances.results }}"
  
    - name: Create Route 53 record for frontend with public ip with zone name only
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ zone }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        overwrite: yes
        wait: true
      loop: "{{ ec2_instances.results }}"
      when: item.item == 'frontend'