- name: create three ec2 instances and r53 records for frontend, backend and mysql
  hosts: local
  connection: local 
  vars:
    subnet_id: subnet-03f5d20441ab8be68
    sg_id: "sg-074acfbaac90a04bc"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
      - mysql
      - backend
      - frontend
  tasks:
    - name: Launch EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: "t3.micro"
        image_id: "{{ ami_id }}"
        vpc_subnet_id: "{{ subnet_id }}"
        security_group: "{{ sg_id }}"
      loop: "{{ instances }}"
      register: ec2_instances