- name: create three ec2 instances and r53 records for frontend, backend and mysql
  hosts: local
  connection: local 
  vars:
    subnet_id: subnet-03f5d20441ab8be68
    sg_id: "sg-074acfbaac90a04bc"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
      - mysql
      - backend
      - frontend
    zone: buddymarket.shop
  tasks:
    - name: Launch EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: "t3.micro"
        image_id: "{{ ami_id }}"
        vpc_subnet_id: "{{ subnet_id }}"
        security_group: "{{ sg_id }}"
      loop: "{{ instances }}"
      register: ec2_instances

    - name: Print the output of launched instances
      debug:
        var: ec2_instances.results

    - name: Create Route 53 records for frontend with public ip and with record with zone name only, backend with private ip and mysql with private ip
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ item.name }}.{{ zone }}"
        type: A
        ttl: 2
        value: "{{ item.ip }}"
      loop:
        - name: frontend
          ip: "{{ ec2_instances.results[2].instance.public_ip_address }}"
        - name: backend
          ip: "{{ ec2_instances.results[1].instance.private_ip_address }}"
        - name: mysql
          ip: "{{ ec2_instances.results[0].instance.private_ip_address }}"