- name: Create 3 EC2 Instances and Route53 DNS Records
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    instance_type: "t3.micro"
    ami_id: "ami-09c813fb71547fc4f"              # Amazon Linux 2 AMI (ap-south-1)
    zone_name: "buddymarket.shop"

    ec2_instances:
      - name: "frontend"
        dns_record: "buddymarket.shop"
      - name: "backend"
        dns_record: "backend.buddymarket.shop"
      - name: "mysql"
        dns_record: "mysql.buddymarket.shop"

  tasks:

    - name: Launch EC2 instance for each component
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        subnet_id: "subnet-03f5d20441ab8be68"  # Replace with your subnet ID
        wait: yes
        tags:
          Name: "{{ item.name }}"
      loop: "{{ ec2_instances }}"
      register: created_instances

    - name: Show all created instance details
      debug:
        var: created_instances

    - name: Create Route53 DNS records for each EC2 instance
      amazon.aws.route53:
        state: present
        zone: "{{ zone_name }}"
        record: "{{ item.item.dns_record }}"
        type: A
        ttl: 300
        value: "{{ item.instances[0].public_ip_address }}"
      loop: "{{ created_instances.results }}"
      register: dns_records

    - name: Show DNS record creation output
      debug:
        var: dns_records